# https://starship.rs/config/
[aws]
disabled = true

[azure]
disabled = true

[buf]
disabled = true

#[bun]
#disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[deno]
disabled = true

[directory]
truncation_length = 8
truncation_symbol = "…/"
fish_style_pwd_dir_length = 3
style = 'bold 28'

[elixir]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

#[guix_shell]
#disabled = true

[haskell]
disabled = true

#[haxe]
#disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

#[meson]
#disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

#[opa]
#disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[scala]
disabled = true

[singularity]
disabled = true

[spack]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
